[workspace]
[package]
version = "0.1.0"
name = "sp1-vectorx-primitives"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
avail-subxt = { git = "https://github.com/availproject/avail.git", tag = "v2.0.0.0-rc4" }
subxt = "0.34"
sp-core = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-2", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "full",
    "bit-vec",
] }
alloy-sol-types = "0.4.2"
alloy-primitives = "0.4.2"
anyhow = "1.0.68"
clap = "4.4.9"
futures = "0.3.30"
async-trait = "0.1.77"
ed25519-dalek = "2.1.1"
