[workspace]
[package]
version = "0.1.0"
name = "sp1-vectorx-script"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }
ed25519-consensus = { version = "2", default-features = false }
rand = "0.8"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }
